import { calculateFocalLength, calculateLensPower, calculateLensSystem } from './physics.js';
import { createLensDiagram } from './diagram.js';
import { createLensScene } from './scene.js';

const $=id=>document.getElementById(id),sceneElement=$('scene'),sceneShell=$('scene-shell');
const state={lensType:'converging',profile:'bi',focalLength:20,objectDistance:35,objectHeight:10,view:'2d',rays:true,virtual:true,grid:true,stepMode:false,step:9,control:'focal'};
const diagram=createLensDiagram($('diagram')),three=createLensScene($('three-scene'));
const inputs={distance:$('object-distance'),distanceNumber:$('object-distance-number'),height:$('object-height'),heightNumber:$('object-height-number'),focal:$('focal-length'),focalNumber:$('focal-number'),power:$('power'),powerNumber:$('power-number'),distance3d:$('object-distance-3d')};
const STEPS=[['Eje y lente','Partimos del eje óptico y del plano principal de la lente.'],['Focos','Ubicamos F, F′ y los puntos dobles 2F y 2F′.'],['Objeto','La flecha representa un objeto real situado antes de la lente.'],['Rayo paralelo','El primer rayo llega paralelo al eje y cambia de dirección según la lente.'],['Rayo central','El rayo que atraviesa el centro óptico no se desvía.'],['Rayo focal','El tercer rayo completa la construcción geométrica.'],['Intersección','La intersección de rayos, o de sus prolongaciones, determina la imagen.'],['Cotas','Comparamos las distancias y alturas con el eje.'],['Resultado','Clasificamos la imagen y verificamos la ecuación de lente delgada.']];
const PRESETS={beyond:{lensType:'converging',objectDistance:55},at2f:{lensType:'converging',objectDistance:40},between:{lensType:'converging',objectDistance:30},atf:{lensType:'converging',objectDistance:20},inside:{lensType:'converging',objectDistance:12},diverging:{lensType:'diverging',objectDistance:35}};

function format(value,digits=1){if(!Number.isFinite(value))return '∞';return Number(value).toLocaleString('es-AR',{minimumFractionDigits:digits,maximumFractionDigits:digits});}
function classification(result){if(result.atInfinity)return 'Imagen en el infinito';const orientation=result.isUpright?'derecha':'invertida',size={larger:'mayor',smaller:'menor',same:'igual'}[result.sizeRelation];return `Imagen ${result.isReal?'real':'virtual'}, ${orientation} y ${size}`;}
function explanation(result){const cases={
  'beyond-2f':"Como el objeto está más allá de 2F, la lente convergente forma una imagen real, invertida y menor entre F′ y 2F′.",
  'at-2f':"Con el objeto en 2F, la imagen aparece en 2F′, real, invertida y del mismo tamaño.",
  'between-f-and-2f':"Al estar entre F y 2F, el objeto produce una imagen real, invertida y aumentada más allá de 2F′.",
  'at-f':"Con el objeto en F, los rayos emergen paralelos y la imagen se encuentra en el infinito.",
  'inside-f':"Dentro de F, las prolongaciones se cruzan del lado del objeto: la imagen es virtual, derecha y aumentada.",
  diverging:"La lente divergente forma siempre una imagen virtual, derecha y menor entre la lente y el foco virtual."
  };return cases[result.case];}
function signed(value){return value>0?`+${format(value)}`:format(value);}
function result(){return calculateLensSystem(state);}
function update(){const r=result(),power=calculateLensPower(r.focalLength/100);
  inputs.distance.value=inputs.distanceNumber.value=state.objectDistance;inputs.height.value=inputs.heightNumber.value=state.objectHeight;inputs.focal.value=inputs.focalNumber.value=Math.abs(state.focalLength);inputs.power.value=inputs.powerNumber.value=Math.abs(power).toFixed(1);inputs.distance3d.value=state.objectDistance;$('object-distance-3d-value').textContent=`${format(state.objectDistance)} cm`;
  document.querySelectorAll('[data-lens]').forEach(b=>{const active=b.dataset.lens===state.lensType;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});
  const profile=$('profile');if(profile.dataset.type!==state.lensType){profile.innerHTML=state.lensType==='converging'?'<option value="bi">Biconvexa</option><option value="plano">Plano-convexa</option><option value="meniscus">Menisco convergente</option>':'<option value="bi">Bicóncava</option><option value="plano">Plano-cóncava</option><option value="meniscus">Menisco divergente</option>';profile.dataset.type=state.lensType;}profile.value=state.profile;
  $('status-text').textContent=classification(r);$('explanation').textContent=explanation(r);$('metric-di').textContent=r.atInfinity?'∞':`${signed(r.imageDistance)} cm`;$('metric-hi').textContent=r.atInfinity?'∞':`${signed(r.imageHeight)} cm`;$('metric-m').textContent=r.atInfinity?'∞':signed(r.magnification);$('metric-region').textContent=r.region;
  $('lens-equation').textContent=r.atInfinity?`1/${format(r.focalLength)} = 1/${format(r.objectDistance)} + 1/∞`:`1/${format(r.focalLength)} = 1/${format(r.objectDistance)} + 1/${format(r.imageDistance)}  [cm⁻¹]`;
  $('magnification-equation').textContent=r.atInfinity?'m no es finito':`m = −(${format(r.imageDistance)}/${format(r.objectDistance)}) = ${signed(r.magnification)}`;
  $('scene-mode').textContent=r.atInfinity?'RAYOS EMERGENTES PARALELOS':state.view==='2d'?'ARRASTRÁ EL OBJETO':'EXPLORÁ EL BANCO ÓPTICO';$('scene-description').textContent=`Lente ${state.lensType==='converging'?'convergente':'divergente'}. Objeto a ${format(state.objectDistance)} centímetros. ${classification(r)}. ${explanation(r)}`;
  diagram.render(r,{rays:state.rays,virtual:state.virtual,grid:state.grid,step:state.stepMode?state.step:9});three.update(r,{rays:state.rays,virtual:state.virtual,profile:state.profile});three.setGrid(state.grid);three.render();updateSteps();
}
function setState(values){Object.assign(state,values);state.focalLength=Math.abs(state.focalLength)*(state.lensType==='converging'?1:-1);update();}
for(const [range,number,key] of [[inputs.distance,inputs.distanceNumber,'objectDistance'],[inputs.height,inputs.heightNumber,'objectHeight'],[inputs.focal,inputs.focalNumber,'focalLength']]){range.addEventListener('input',e=>setState({[key]:Number(e.target.value)}));number.addEventListener('input',e=>{if(e.target.validity.valid)setState({[key]:Number(e.target.value)});});}
inputs.power.addEventListener('input',e=>setPower(e.target.value));inputs.powerNumber.addEventListener('input',e=>{if(e.target.validity.valid)setPower(e.target.value);});inputs.distance3d.addEventListener('input',e=>setState({objectDistance:Number(e.target.value)}));
function setPower(value){const signedPower=Math.abs(Number(value))*(state.lensType==='converging'?1:-1);setState({focalLength:calculateFocalLength(signedPower)*100});}
document.querySelector('.segmented').addEventListener('click',e=>{const b=e.target.closest('[data-lens]');if(b)setState({lensType:b.dataset.lens,profile:'bi'});});$('profile').addEventListener('change',e=>setState({profile:e.target.value}));document.querySelector('.mode-switch').addEventListener('click',e=>{const b=e.target.closest('[data-control]');if(!b)return;state.control=b.dataset.control;document.querySelectorAll('[data-control]').forEach(x=>x.classList.toggle('active',x===b));$('focal-control').hidden=state.control!=='focal';$('power-control').hidden=state.control!=='power';});
$('presets').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(!b)return;setState({...PRESETS[b.dataset.preset],focalLength:20});});$('reset').addEventListener('click',()=>setState({lensType:'converging',focalLength:20,objectDistance:35,objectHeight:10,rays:true,virtual:true,grid:true,stepMode:false,step:9}));
for(const [id,key] of [['toggle-rays','rays'],['toggle-virtual','virtual'],['toggle-grid','grid']])$(id).addEventListener('click',e=>{state[key]=!state[key];e.currentTarget.setAttribute('aria-pressed',state[key]);update();});
function updateSteps(){if(!state.stepMode)return;const [title,copy]=STEPS[state.step-1];$('step-title').textContent=title;$('step-copy').textContent=copy;$('step-count').textContent=`${state.step} / 9`;$('step-prev').disabled=state.step===1;$('step-next').disabled=state.step===9;}
$('step-mode').addEventListener('click',()=>{state.stepMode=!state.stepMode;state.step=state.stepMode?1:9;$('steps').hidden=!state.stepMode;update();});$('step-prev').addEventListener('click',()=>{state.step=Math.max(1,state.step-1);update();});$('step-next').addEventListener('click',()=>{state.step=Math.min(9,state.step+1);update();});$('step-skip').addEventListener('click',()=>{state.step=9;update();});
document.querySelector('.view-toggle').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;sceneShell.classList.toggle('view-3d',state.view==='3d');document.querySelectorAll('[data-view]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active);});update3dControls();update();});
function pointerValue(event){const rect=sceneElement.getBoundingClientRect(),cx=rect.left+rect.width/2,cy=rect.top+rect.height/2;return{distance:Math.max(8,Math.min(80,(cx-event.clientX)/(rect.width*.43/85))),height:Math.max(2,Math.min(18,(cy-event.clientY)/(rect.width*.43/85)))};}
let pointer=null,dragHeight=false;sceneElement.addEventListener('pointerdown',e=>{if(state.view==='3d'||e.button!==0)return;const value=pointerValue(e),nearObject=Math.abs(value.distance-state.objectDistance)<7;dragHeight=nearObject&&e.clientY<sceneElement.getBoundingClientRect().top+sceneElement.clientHeight/2;pointer=e.pointerId;sceneElement.setPointerCapture(pointer);sceneElement.classList.add('dragging');setState(dragHeight?{objectHeight:value.height}:{objectDistance:value.distance});});sceneElement.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;e.preventDefault();const value=pointerValue(e);setState(dragHeight?{objectHeight:value.height}:{objectDistance:value.distance});});function release(e){if(e.pointerId===pointer){pointer=null;sceneElement.classList.remove('dragging');}}sceneElement.addEventListener('pointerup',release);sceneElement.addEventListener('pointercancel',release);sceneElement.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft'||e.key==='ArrowRight')setState({objectDistance:Math.max(8,Math.min(80,state.objectDistance+(e.key==='ArrowLeft'?1:-1)))});else setState({objectHeight:Math.max(2,Math.min(18,state.objectHeight+(e.key==='ArrowUp'?.5:-.5)))});});
let fallbackFullscreen=false,previousScroll=0;const fullscreenButton=$('fullscreen');function fullscreenState(active){fullscreenButton.setAttribute('aria-pressed',active);fullscreenButton.querySelector('.fullscreen-label').textContent=active?'Salir':'Pantalla completa';update3dControls();}function fallback(active){fallbackFullscreen=active;if(active){previousScroll=scrollY;sceneShell.style.setProperty('--fullscreen-height',`${visualViewport?.height||innerHeight}px`);sceneShell.classList.add('fullscreen-fallback');document.body.classList.add('fullscreen-open');history.pushState({lensFullscreen:true},'');}else{sceneShell.classList.remove('fullscreen-fallback');document.body.classList.remove('fullscreen-open');scrollTo(0,previousScroll);}fullscreenState(active);}fullscreenButton.addEventListener('click',async()=>{if(fallbackFullscreen)return fallback(false);if(document.fullscreenElement)return document.exitFullscreen();if(sceneShell.requestFullscreen)try{return await sceneShell.requestFullscreen();}catch{}fallback(true);});document.addEventListener('fullscreenchange',()=>fullscreenState(document.fullscreenElement===sceneShell));addEventListener('popstate',()=>fallbackFullscreen&&fallback(false));visualViewport?.addEventListener('resize',()=>fallbackFullscreen&&sceneShell.style.setProperty('--fullscreen-height',`${visualViewport.height}px`));
function update3dControls(){$('controls-3d').classList.toggle('visible',state.view==='3d'&&(fallbackFullscreen||document.fullscreenElement===sceneShell));}
const stick=$('camera-stick'),knob=stick.querySelector('i');let stickId=null,vector={x:0,y:0},frame,time=0;function stickMove(e){const r=stick.getBoundingClientRect();vector={x:Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/(r.width*.34))),y:Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/(r.height*.34)))};knob.style.transform=`translate(${vector.x*26}px,${vector.y*26}px)`;}function stickLoop(t){if(stickId==null)return;const scale=Math.min(2,(t-time)/16.67||1);time=t;three.orbitCamera(Math.abs(vector.x)<.08?0:vector.x*.025*scale,Math.abs(vector.y)<.08?0:vector.y*.02*scale);frame=requestAnimationFrame(stickLoop);}stick.addEventListener('pointerdown',e=>{stickId=e.pointerId;stick.setPointerCapture(stickId);stickMove(e);time=performance.now();frame=requestAnimationFrame(stickLoop);});stick.addEventListener('pointermove',e=>{if(e.pointerId===stickId){e.preventDefault();stickMove(e);}});function releaseStick(e){if(e.pointerId!==stickId)return;stickId=null;cancelAnimationFrame(frame);vector={x:0,y:0};knob.style.transform='translate(0,0)';}stick.addEventListener('pointerup',releaseStick);stick.addEventListener('pointercancel',releaseStick);
new ResizeObserver(update).observe(sceneElement);addEventListener('pagehide',()=>three.dispose(),{once:true});update();
