import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const RAY_COLORS=[0xc41234,0x29a7ad,0xe7a51b];
export function createLensScene(container){
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x111518);
  const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(8,5.5,11);
  const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;container.append(renderer.domElement);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.minDistance=6;controls.maxDistance=22;controls.enableDamping=false;controls.addEventListener('change',render);
  const geometries=[],materials=[];const geo=x=>(geometries.push(x),x),mat=x=>(materials.push(x),x);
  scene.add(new THREE.HemisphereLight(0xffffff,0x30383b,2.4));const key=new THREE.DirectionalLight(0xffffff,2.1);key.position.set(-4,7,6);scene.add(key);
  const bench=new THREE.Mesh(geo(new THREE.BoxGeometry(15,.18,3.4)),mat(new THREE.MeshStandardMaterial({color:0x252a2d,roughness:.62,metalness:.55})));bench.position.y=-2.35;scene.add(bench);
  const railMat=mat(new THREE.MeshStandardMaterial({color:0xb8bec0,roughness:.25,metalness:.8}));for(const z of [-1.1,1.1]){const rail=new THREE.Mesh(geo(new THREE.CylinderGeometry(.07,.07,14,16)),railMat);rail.rotation.z=Math.PI/2;rail.position.set(0,-2.05,z);scene.add(rail);}
  const axis=new THREE.Mesh(geo(new THREE.CylinderGeometry(.012,.012,15,8)),mat(new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.38})));axis.rotation.z=Math.PI/2;scene.add(axis);
  const grid=new THREE.GridHelper(15,30,0x566064,0x343b3e);grid.position.y=-2.23;scene.add(grid);grid.material.transparent=true;grid.material.opacity=.38;materials.push(grid.material);
  const lensGroup=new THREE.Group();scene.add(lensGroup);const lensMaterial=mat(new THREE.MeshPhysicalMaterial({color:0xb9e5df,transparent:true,opacity:.42,transmission:.36,roughness:.08,metalness:0,ior:1.5,thickness:.65,side:THREE.DoubleSide,depthWrite:false}));
  const mountMaterial=mat(new THREE.MeshStandardMaterial({color:0x343a3e,roughness:.35,metalness:.72}));const ring=new THREE.Mesh(geo(new THREE.TorusGeometry(2.02,.11,18,64)),mountMaterial);ring.rotation.y=Math.PI/2;lensGroup.add(ring);const post=new THREE.Mesh(geo(new THREE.CylinderGeometry(.09,.11,2.2,20)),mountMaterial);post.position.y=-2.85;lensGroup.add(post);
  let lensMesh,currentLensKey='';const lensGeometries=new Map();
  function lensGeometry(type,profile='bi'){const front=[],back=[];for(let i=0;i<=28;i++){const radius=i*1.9/28,n=radius/1.9,curve=1-n*n;let frontThickness,backThickness;if(type==='converging'){frontThickness=.1+.5*curve;backThickness=profile==='plano'?.1:profile==='meniscus'?-.04+.26*curve:.1+.5*curve;}else{frontThickness=.48-.36*curve;backThickness=profile==='plano'?.48:profile==='meniscus'?.27-.18*curve:.48-.36*curve;}front.push(new THREE.Vector2(radius,frontThickness));back.unshift(new THREE.Vector2(radius,-backThickness));}return geo(new THREE.LatheGeometry([...front,...back],72));}
  function replaceLens(type,profile){const key=`${type}-${profile}`;if(key===currentLensKey)return;if(lensMesh)lensGroup.remove(lensMesh);if(!lensGeometries.has(key))lensGeometries.set(key,lensGeometry(type,profile));lensMesh=new THREE.Mesh(lensGeometries.get(key),lensMaterial);lensMesh.rotation.z=-Math.PI/2;lensGroup.add(lensMesh);currentLensKey=key;}replaceLens('converging','bi');
  const objectGroup=arrowAssembly(0xc41234,'Objeto'),imageGroup=arrowAssembly(0xede7d3,'Imagen');scene.add(objectGroup,imageGroup);
  function arrowAssembly(color){const group=new THREE.Group(),shaft=new THREE.Mesh(geo(new THREE.CylinderGeometry(.045,.045,1,14)),mat(new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.35}))),tip=new THREE.Mesh(geo(new THREE.ConeGeometry(.16,.36,20)),shaft.material),base=new THREE.Mesh(geo(new THREE.CylinderGeometry(.26,.32,.13,24)),mountMaterial);shaft.position.y=.5;tip.position.y=1.18;base.position.y=.03;group.add(shaft,tip,base);return group;}
  const focalObjects=[];for(let i=0;i<4;i++){const marker=new THREE.Mesh(geo(new THREE.SphereGeometry(.09,18,12)),mat(new THREE.MeshBasicMaterial({color:i===0||i===3?0x8f999b:0xffffff})));scene.add(marker);focalObjects.push(marker);}
  const rayGroups=RAY_COLORS.map(color=>{const g=new THREE.Group();scene.add(g);return g;}),virtualGroup=new THREE.Group();scene.add(virtualGroup);
  const rayGeometry=geo(new THREE.CylinderGeometry(.025,.025,1,10)),virtualGeometry=geo(new THREE.CylinderGeometry(.018,.018,1,10));
  const rayMaterials=RAY_COLORS.map(color=>mat(new THREE.MeshBasicMaterial({color}))),virtualMaterials=RAY_COLORS.map(color=>mat(new THREE.MeshBasicMaterial({color,transparent:true,opacity:.28})));
  function cylinderLine(group,a,b,index,virtual=false){const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),direction=end.clone().sub(start),mesh=new THREE.Mesh(virtual?virtualGeometry:rayGeometry,virtual?virtualMaterials[index]:rayMaterials[index]);mesh.position.copy(start.clone().add(end).multiplyScalar(.5));mesh.scale.y=direction.length();mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),direction.normalize());group.add(mesh);}
  function clearGroup(group){group.clear();}
  function update(result,options={}){replaceLens(result.lensType,options.profile);const scale=.07,xObj=-result.objectDistance*scale,hObj=result.objectHeight*scale;objectGroup.position.set(xObj,0,0);objectGroup.scale.setScalar(Math.max(.45,hObj/1.35));imageGroup.visible=!result.atInfinity&&Math.abs(result.imageDistance)<100;imageGroup.position.set(result.imageDistance*scale,0,0);imageGroup.scale.set(.65,Math.max(.25,Math.abs(result.imageHeight)*scale/1.35),.65);imageGroup.rotation.z=result.imageHeight<0?Math.PI:0;const f=Math.abs(result.focalLength)*scale;[-2*f,-f,f,2*f].forEach((x,i)=>focalObjects[i].position.x=x);rayGroups.forEach(clearGroup);clearGroup(virtualGroup);if(options.rays!==false){const xEnd=5.7,yAtImage=result.atInfinity?0:result.imageHeight*scale;const imageX=result.atInfinity?xEnd:Math.max(-5.7,Math.min(5.7,result.imageDistance*scale));const lensHits=[hObj,0,yAtImage];const starts=[[xObj,hObj,0],[xObj,hObj,0],[xObj,hObj,0]];for(let i=0;i<3;i++){cylinderLine(rayGroups[i],starts[i],[0,lensHits[i],0],i);let target;if(result.atInfinity)target=[xEnd,lensHits[i]-hObj*xEnd/xObj,0];else if(result.isVirtual){const di=result.imageDistance*scale;target=[xEnd,lensHits[i]+(yAtImage-lensHits[i])/di*xEnd,0];}else target=[imageX,yAtImage*(imageX/(result.imageDistance*scale)),0];cylinderLine(rayGroups[i],[0,lensHits[i],0],target,i);if(result.isVirtual&&options.virtual!==false)cylinderLine(virtualGroup,[0,lensHits[i],0],[result.imageDistance*scale,yAtImage,0],i,true);}}
  }
  function orbitCamera(dx,dy){const offset=camera.position.clone().sub(controls.target),s=new THREE.Spherical().setFromVector3(offset);s.theta-=dx;s.phi=THREE.MathUtils.clamp(s.phi+dy,.2,Math.PI-.3);camera.position.copy(controls.target).add(new THREE.Vector3().setFromSpherical(s));camera.lookAt(controls.target);controls.update();render();}
  function render(){renderer.render(scene,camera);}function resize(){const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();render();}const observer=new ResizeObserver(resize);observer.observe(container);resize();
  return{update,orbitCamera,render,setGrid(value){grid.visible=value;render();},dispose(){observer.disconnect();controls.dispose();geometries.forEach(x=>x.dispose());materials.forEach(x=>x.dispose());renderer.dispose();}};
}
